import { createEntry, day, offset, uid } from "./model";
import { Entry } from "@/types";
export function demoEntries(): Entry[] {
  const rows: Entry[] = [
    createEntry("events", {
      title: "Team catch-up",
      date: day(),
      time: "10:30",
      endTime: "11:00",
      category: "Work",
      location: "Microsoft Teams",
      colour: "blue",
    }),
    createEntry("events", {
      title: "A little time for yourself",
      date: day(),
      time: "18:30",
      endTime: "19:30",
      category: "Personal",
      location: "Evening walk",
      colour: "teal",
    }),
    createEntry("tasks", {
      title: "Book an eye test",
      date: day(),
      priority: "High",
      category: "Health",
      reminder: true,
    }),
    createEntry("tasks", {
      title: "Pick up a few groceries",
      date: day(),
      priority: "Normal",
      category: "Personal",
    }),
    createEntry("tasks", {
      title: "Plan the weekend",
      date: day(),
      priority: "Low",
      category: "Personal",
    }),
    createEntry("bills", {
      title: "Vodafone",
      company: "Vodafone",
      amount: 69,
      date: offset(1),
      recurrence: "monthly",
      category: "Phone",
    }),
    createEntry("bills", {
      title: "Car insurance",
      company: "Insurance",
      amount: 128,
      date: offset(5),
      recurrence: "monthly",
      category: "Insurance",
    }),
    createEntry("expenses", {
      title: "Lunch at the local",
      merchant: "Local café",
      amount: 18.5,
      date: day(),
      time: "12:45",
      category: "Food",
    }),
    createEntry("expenses", {
      title: "Groceries",
      merchant: "Woolworths",
      amount: 65.7,
      date: day(),
      time: "16:15",
      category: "Groceries",
    }),
    createEntry("expenses", {
      title: "Train journeys",
      amount: 38.8,
      date: offset(-3),
      category: "Transport",
    }),
    createEntry("deliveries", {
      title: "iPhone case",
      retailer: "Amazon",
      courier: "Australia Post",
      date: day(),
      status: "Out for delivery",
    }),
    createEntry("notes", {
      title: "A little reminder",
      body: "Call Apple about the battery.\nA small thing off the list is still progress.",
      pinned: true,
    }),
    createEntry("products", {
      title: "Ray-Ban Wayfarer",
      retailer: "The Iconic",
      category: "Style",
      price: 219,
      originalPrice: 299,
      targetPrice: 180,
      availability: "In stock",
      alert: "Any price drop",
      status: "Watching",
    }),
    createEntry("products", {
      title: "Sony WH-1000XM6",
      retailer: "JB Hi-Fi",
      category: "Tech",
      price: 499,
      originalPrice: 649,
      targetPrice: 400,
      availability: "In stock",
      alert: "Any price drop",
      status: "Watching",
    }),
  ];
  return rows;
}
